#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassCreator
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Uitvaartwensen")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::ClassCreator.Properties.Settings.Default.UitvaartwensenConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Wen> Wens
		{
			get
			{
				return this.GetTable<Wen>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Wens")]
	public partial class Wen
	{
		
		private int _Id;
		
		private string _Achternaam;
		
		private string _Tussenvoegsels;
		
		private string _Voornaam;
		
		private string _Email;
		
		private string _Adres;
		
		private string _Postcode;
		
		private string _Woonplaats;
		
		private string _Telefoon;
		
		private string _Geboortedatum;
		
		private string _Geboorteplaats;
		
		private string _Geloofsovertuiging;
		
		private System.Nullable<bool> _Pacemaker;
		
		private System.Nullable<bool> _Donorcodicil;
		
		private string _Notaris;
		
		private string _VestigingsplaatsNotaris;
		
		private System.Nullable<System.DateTime> _DatumTestament;
		
		private string _Naam1;
		
		private string _Adres1;
		
		private string _Telefoon1;
		
		private string _Naam2;
		
		private string _Adres2;
		
		private string _Telefoon2;
		
		private string _Naam3;
		
		private string _Adres3;
		
		private string _Telefoon3;
		
		private string _Naam4;
		
		private string _Adres4;
		
		private string _Telefoon4;
		
		private string _Begrafenis;
		
		private System.Nullable<bool> _BeslotenKring;
		
		private string _Condoleance;
		
		private System.Nullable<bool> _Voorganger;
		
		private System.Nullable<bool> _NaamVoorganger;
		
		private System.Nullable<bool> _Liturgie;
		
		private System.Nullable<bool> _Organist;
		
		private System.Nullable<bool> _DienstOpBegraafplaats;
		
		private string _Muziek1;
		
		private string _Muziek2;
		
		private string _Muziek3;
		
		private string _Muziek4;
		
		private string _Muziek5;
		
		private string _Muziek6;
		
		private string _Opname;
		
		private System.Nullable<bool> _Toespraken;
		
		private System.Nullable<bool> _Rouwcirculaires;
		
		private System.Nullable<bool> _Advertentie;
		
		private string _AdvertentieBlad1;
		
		private string _AdvertentieBlad2;
		
		private string _AdvertentieBlad3;
		
		private string _Opbaarlokatie;
		
		private string _OpbaarlokatieElders;
		
		private System.Nullable<bool> _Bedankkaartjes;
		
		private System.Nullable<bool> _BedankAdvertentie;
		
		private string _BedankAdvertentieBladen;
		
		private string _Adressenlijst;
		
		private string _Bloemen;
		
		private string _Begraafplaats;
		
		private string _SoortGraf;
		
		private string _BestaandGraf;
		
		private string _DalenKist;
		
		private string _GedenkMonument;
		
		private string _GebruikAuto;
		
		private string _Crematorium;
		
		private string _Asbestbestemming;
		
		private string _Consumpties;
		
		private string _SoortConsumpties;
		
		private string _Girorekening;
		
		private string _Bankrekening;
		
		private string _Maatschappij1;
		
		private string _Maatschappij2;
		
		private string _Maatschappij3;
		
		private string _Maatschappij4;
		
		private string _Maatschappij5;
		
		private string _Maatschappij6;
		
		private string _Maatschappij7;
		
		private string _Maatschappij8;
		
		private string _OverigeOpmerkingen;
		
		private string _GrafVak;
		
		private string _GrafPlaats;
		
		private string _GrafTelefoon;
		
		private string _Polis1;
		
		private string _Polis2;
		
		private string _Polis3;
		
		private string _Polis4;
		
		private string _Polis5;
		
		private string _Polis6;
		
		private string _Polis7;
		
		private string _Polis8;
		
		public Wen()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Achternaam", DbType="VarChar(50)")]
		public string Achternaam
		{
			get
			{
				return this._Achternaam;
			}
			set
			{
				if ((this._Achternaam != value))
				{
					this._Achternaam = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tussenvoegsels", DbType="VarChar(50)")]
		public string Tussenvoegsels
		{
			get
			{
				return this._Tussenvoegsels;
			}
			set
			{
				if ((this._Tussenvoegsels != value))
				{
					this._Tussenvoegsels = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Voornaam", DbType="VarChar(50)")]
		public string Voornaam
		{
			get
			{
				return this._Voornaam;
			}
			set
			{
				if ((this._Voornaam != value))
				{
					this._Voornaam = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adres", DbType="VarChar(50)")]
		public string Adres
		{
			get
			{
				return this._Adres;
			}
			set
			{
				if ((this._Adres != value))
				{
					this._Adres = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postcode", DbType="VarChar(50)")]
		public string Postcode
		{
			get
			{
				return this._Postcode;
			}
			set
			{
				if ((this._Postcode != value))
				{
					this._Postcode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Woonplaats", DbType="VarChar(50)")]
		public string Woonplaats
		{
			get
			{
				return this._Woonplaats;
			}
			set
			{
				if ((this._Woonplaats != value))
				{
					this._Woonplaats = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefoon", DbType="VarChar(50)")]
		public string Telefoon
		{
			get
			{
				return this._Telefoon;
			}
			set
			{
				if ((this._Telefoon != value))
				{
					this._Telefoon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Geboortedatum", DbType="VarChar(50)")]
		public string Geboortedatum
		{
			get
			{
				return this._Geboortedatum;
			}
			set
			{
				if ((this._Geboortedatum != value))
				{
					this._Geboortedatum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Geboorteplaats", DbType="VarChar(50)")]
		public string Geboorteplaats
		{
			get
			{
				return this._Geboorteplaats;
			}
			set
			{
				if ((this._Geboorteplaats != value))
				{
					this._Geboorteplaats = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Geloofsovertuiging", DbType="VarChar(50)")]
		public string Geloofsovertuiging
		{
			get
			{
				return this._Geloofsovertuiging;
			}
			set
			{
				if ((this._Geloofsovertuiging != value))
				{
					this._Geloofsovertuiging = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pacemaker", DbType="Bit")]
		public System.Nullable<bool> Pacemaker
		{
			get
			{
				return this._Pacemaker;
			}
			set
			{
				if ((this._Pacemaker != value))
				{
					this._Pacemaker = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Donorcodicil", DbType="Bit")]
		public System.Nullable<bool> Donorcodicil
		{
			get
			{
				return this._Donorcodicil;
			}
			set
			{
				if ((this._Donorcodicil != value))
				{
					this._Donorcodicil = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notaris", DbType="VarChar(50)")]
		public string Notaris
		{
			get
			{
				return this._Notaris;
			}
			set
			{
				if ((this._Notaris != value))
				{
					this._Notaris = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VestigingsplaatsNotaris", DbType="VarChar(50)")]
		public string VestigingsplaatsNotaris
		{
			get
			{
				return this._VestigingsplaatsNotaris;
			}
			set
			{
				if ((this._VestigingsplaatsNotaris != value))
				{
					this._VestigingsplaatsNotaris = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DatumTestament", DbType="DateTime")]
		public System.Nullable<System.DateTime> DatumTestament
		{
			get
			{
				return this._DatumTestament;
			}
			set
			{
				if ((this._DatumTestament != value))
				{
					this._DatumTestament = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Naam1", DbType="VarChar(50)")]
		public string Naam1
		{
			get
			{
				return this._Naam1;
			}
			set
			{
				if ((this._Naam1 != value))
				{
					this._Naam1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adres1", DbType="VarChar(50)")]
		public string Adres1
		{
			get
			{
				return this._Adres1;
			}
			set
			{
				if ((this._Adres1 != value))
				{
					this._Adres1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefoon1", DbType="VarChar(50)")]
		public string Telefoon1
		{
			get
			{
				return this._Telefoon1;
			}
			set
			{
				if ((this._Telefoon1 != value))
				{
					this._Telefoon1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Naam2", DbType="VarChar(50)")]
		public string Naam2
		{
			get
			{
				return this._Naam2;
			}
			set
			{
				if ((this._Naam2 != value))
				{
					this._Naam2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adres2", DbType="VarChar(50)")]
		public string Adres2
		{
			get
			{
				return this._Adres2;
			}
			set
			{
				if ((this._Adres2 != value))
				{
					this._Adres2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefoon2", DbType="VarChar(50)")]
		public string Telefoon2
		{
			get
			{
				return this._Telefoon2;
			}
			set
			{
				if ((this._Telefoon2 != value))
				{
					this._Telefoon2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Naam3", DbType="VarChar(50)")]
		public string Naam3
		{
			get
			{
				return this._Naam3;
			}
			set
			{
				if ((this._Naam3 != value))
				{
					this._Naam3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adres3", DbType="VarChar(50)")]
		public string Adres3
		{
			get
			{
				return this._Adres3;
			}
			set
			{
				if ((this._Adres3 != value))
				{
					this._Adres3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefoon3", DbType="VarChar(50)")]
		public string Telefoon3
		{
			get
			{
				return this._Telefoon3;
			}
			set
			{
				if ((this._Telefoon3 != value))
				{
					this._Telefoon3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Naam4", DbType="VarChar(50)")]
		public string Naam4
		{
			get
			{
				return this._Naam4;
			}
			set
			{
				if ((this._Naam4 != value))
				{
					this._Naam4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adres4", DbType="VarChar(50)")]
		public string Adres4
		{
			get
			{
				return this._Adres4;
			}
			set
			{
				if ((this._Adres4 != value))
				{
					this._Adres4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefoon4", DbType="VarChar(50)")]
		public string Telefoon4
		{
			get
			{
				return this._Telefoon4;
			}
			set
			{
				if ((this._Telefoon4 != value))
				{
					this._Telefoon4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Begrafenis", DbType="VarChar(50)")]
		public string Begrafenis
		{
			get
			{
				return this._Begrafenis;
			}
			set
			{
				if ((this._Begrafenis != value))
				{
					this._Begrafenis = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BeslotenKring", DbType="Bit")]
		public System.Nullable<bool> BeslotenKring
		{
			get
			{
				return this._BeslotenKring;
			}
			set
			{
				if ((this._BeslotenKring != value))
				{
					this._BeslotenKring = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Condoleance", DbType="VarChar(50)")]
		public string Condoleance
		{
			get
			{
				return this._Condoleance;
			}
			set
			{
				if ((this._Condoleance != value))
				{
					this._Condoleance = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Voorganger", DbType="Bit")]
		public System.Nullable<bool> Voorganger
		{
			get
			{
				return this._Voorganger;
			}
			set
			{
				if ((this._Voorganger != value))
				{
					this._Voorganger = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NaamVoorganger", DbType="Bit")]
		public System.Nullable<bool> NaamVoorganger
		{
			get
			{
				return this._NaamVoorganger;
			}
			set
			{
				if ((this._NaamVoorganger != value))
				{
					this._NaamVoorganger = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Liturgie", DbType="Bit")]
		public System.Nullable<bool> Liturgie
		{
			get
			{
				return this._Liturgie;
			}
			set
			{
				if ((this._Liturgie != value))
				{
					this._Liturgie = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Organist", DbType="Bit")]
		public System.Nullable<bool> Organist
		{
			get
			{
				return this._Organist;
			}
			set
			{
				if ((this._Organist != value))
				{
					this._Organist = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienstOpBegraafplaats", DbType="Bit")]
		public System.Nullable<bool> DienstOpBegraafplaats
		{
			get
			{
				return this._DienstOpBegraafplaats;
			}
			set
			{
				if ((this._DienstOpBegraafplaats != value))
				{
					this._DienstOpBegraafplaats = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Muziek1", DbType="VarChar(50)")]
		public string Muziek1
		{
			get
			{
				return this._Muziek1;
			}
			set
			{
				if ((this._Muziek1 != value))
				{
					this._Muziek1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Muziek2", DbType="VarChar(50)")]
		public string Muziek2
		{
			get
			{
				return this._Muziek2;
			}
			set
			{
				if ((this._Muziek2 != value))
				{
					this._Muziek2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Muziek3", DbType="VarChar(50)")]
		public string Muziek3
		{
			get
			{
				return this._Muziek3;
			}
			set
			{
				if ((this._Muziek3 != value))
				{
					this._Muziek3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Muziek4", DbType="VarChar(50)")]
		public string Muziek4
		{
			get
			{
				return this._Muziek4;
			}
			set
			{
				if ((this._Muziek4 != value))
				{
					this._Muziek4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Muziek5", DbType="VarChar(50)")]
		public string Muziek5
		{
			get
			{
				return this._Muziek5;
			}
			set
			{
				if ((this._Muziek5 != value))
				{
					this._Muziek5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Muziek6", DbType="VarChar(50)")]
		public string Muziek6
		{
			get
			{
				return this._Muziek6;
			}
			set
			{
				if ((this._Muziek6 != value))
				{
					this._Muziek6 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Opname", DbType="VarChar(50)")]
		public string Opname
		{
			get
			{
				return this._Opname;
			}
			set
			{
				if ((this._Opname != value))
				{
					this._Opname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Toespraken", DbType="Bit")]
		public System.Nullable<bool> Toespraken
		{
			get
			{
				return this._Toespraken;
			}
			set
			{
				if ((this._Toespraken != value))
				{
					this._Toespraken = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rouwcirculaires", DbType="Bit")]
		public System.Nullable<bool> Rouwcirculaires
		{
			get
			{
				return this._Rouwcirculaires;
			}
			set
			{
				if ((this._Rouwcirculaires != value))
				{
					this._Rouwcirculaires = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Advertentie", DbType="Bit")]
		public System.Nullable<bool> Advertentie
		{
			get
			{
				return this._Advertentie;
			}
			set
			{
				if ((this._Advertentie != value))
				{
					this._Advertentie = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdvertentieBlad1", DbType="VarChar(50)")]
		public string AdvertentieBlad1
		{
			get
			{
				return this._AdvertentieBlad1;
			}
			set
			{
				if ((this._AdvertentieBlad1 != value))
				{
					this._AdvertentieBlad1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdvertentieBlad2", DbType="VarChar(50)")]
		public string AdvertentieBlad2
		{
			get
			{
				return this._AdvertentieBlad2;
			}
			set
			{
				if ((this._AdvertentieBlad2 != value))
				{
					this._AdvertentieBlad2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdvertentieBlad3", DbType="VarChar(50)")]
		public string AdvertentieBlad3
		{
			get
			{
				return this._AdvertentieBlad3;
			}
			set
			{
				if ((this._AdvertentieBlad3 != value))
				{
					this._AdvertentieBlad3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Opbaarlokatie", DbType="VarChar(50)")]
		public string Opbaarlokatie
		{
			get
			{
				return this._Opbaarlokatie;
			}
			set
			{
				if ((this._Opbaarlokatie != value))
				{
					this._Opbaarlokatie = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OpbaarlokatieElders", DbType="VarChar(50)")]
		public string OpbaarlokatieElders
		{
			get
			{
				return this._OpbaarlokatieElders;
			}
			set
			{
				if ((this._OpbaarlokatieElders != value))
				{
					this._OpbaarlokatieElders = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bedankkaartjes", DbType="Bit")]
		public System.Nullable<bool> Bedankkaartjes
		{
			get
			{
				return this._Bedankkaartjes;
			}
			set
			{
				if ((this._Bedankkaartjes != value))
				{
					this._Bedankkaartjes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BedankAdvertentie", DbType="Bit")]
		public System.Nullable<bool> BedankAdvertentie
		{
			get
			{
				return this._BedankAdvertentie;
			}
			set
			{
				if ((this._BedankAdvertentie != value))
				{
					this._BedankAdvertentie = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BedankAdvertentieBladen", DbType="VarChar(50)")]
		public string BedankAdvertentieBladen
		{
			get
			{
				return this._BedankAdvertentieBladen;
			}
			set
			{
				if ((this._BedankAdvertentieBladen != value))
				{
					this._BedankAdvertentieBladen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adressenlijst", DbType="VarChar(50)")]
		public string Adressenlijst
		{
			get
			{
				return this._Adressenlijst;
			}
			set
			{
				if ((this._Adressenlijst != value))
				{
					this._Adressenlijst = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bloemen", DbType="VarChar(50)")]
		public string Bloemen
		{
			get
			{
				return this._Bloemen;
			}
			set
			{
				if ((this._Bloemen != value))
				{
					this._Bloemen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Begraafplaats", DbType="VarChar(50)")]
		public string Begraafplaats
		{
			get
			{
				return this._Begraafplaats;
			}
			set
			{
				if ((this._Begraafplaats != value))
				{
					this._Begraafplaats = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoortGraf", DbType="VarChar(50)")]
		public string SoortGraf
		{
			get
			{
				return this._SoortGraf;
			}
			set
			{
				if ((this._SoortGraf != value))
				{
					this._SoortGraf = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BestaandGraf", DbType="VarChar(50)")]
		public string BestaandGraf
		{
			get
			{
				return this._BestaandGraf;
			}
			set
			{
				if ((this._BestaandGraf != value))
				{
					this._BestaandGraf = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DalenKist", DbType="VarChar(50)")]
		public string DalenKist
		{
			get
			{
				return this._DalenKist;
			}
			set
			{
				if ((this._DalenKist != value))
				{
					this._DalenKist = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GedenkMonument", DbType="VarChar(50)")]
		public string GedenkMonument
		{
			get
			{
				return this._GedenkMonument;
			}
			set
			{
				if ((this._GedenkMonument != value))
				{
					this._GedenkMonument = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GebruikAuto", DbType="VarChar(50)")]
		public string GebruikAuto
		{
			get
			{
				return this._GebruikAuto;
			}
			set
			{
				if ((this._GebruikAuto != value))
				{
					this._GebruikAuto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Crematorium", DbType="VarChar(50)")]
		public string Crematorium
		{
			get
			{
				return this._Crematorium;
			}
			set
			{
				if ((this._Crematorium != value))
				{
					this._Crematorium = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Asbestbestemming", DbType="VarChar(50)")]
		public string Asbestbestemming
		{
			get
			{
				return this._Asbestbestemming;
			}
			set
			{
				if ((this._Asbestbestemming != value))
				{
					this._Asbestbestemming = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Consumpties", DbType="VarChar(50)")]
		public string Consumpties
		{
			get
			{
				return this._Consumpties;
			}
			set
			{
				if ((this._Consumpties != value))
				{
					this._Consumpties = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoortConsumpties", DbType="VarChar(50)")]
		public string SoortConsumpties
		{
			get
			{
				return this._SoortConsumpties;
			}
			set
			{
				if ((this._SoortConsumpties != value))
				{
					this._SoortConsumpties = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Girorekening", DbType="VarChar(50)")]
		public string Girorekening
		{
			get
			{
				return this._Girorekening;
			}
			set
			{
				if ((this._Girorekening != value))
				{
					this._Girorekening = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bankrekening", DbType="VarChar(50)")]
		public string Bankrekening
		{
			get
			{
				return this._Bankrekening;
			}
			set
			{
				if ((this._Bankrekening != value))
				{
					this._Bankrekening = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maatschappij1", DbType="VarChar(50)")]
		public string Maatschappij1
		{
			get
			{
				return this._Maatschappij1;
			}
			set
			{
				if ((this._Maatschappij1 != value))
				{
					this._Maatschappij1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maatschappij2", DbType="VarChar(50)")]
		public string Maatschappij2
		{
			get
			{
				return this._Maatschappij2;
			}
			set
			{
				if ((this._Maatschappij2 != value))
				{
					this._Maatschappij2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maatschappij3", DbType="VarChar(50)")]
		public string Maatschappij3
		{
			get
			{
				return this._Maatschappij3;
			}
			set
			{
				if ((this._Maatschappij3 != value))
				{
					this._Maatschappij3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maatschappij4", DbType="VarChar(50)")]
		public string Maatschappij4
		{
			get
			{
				return this._Maatschappij4;
			}
			set
			{
				if ((this._Maatschappij4 != value))
				{
					this._Maatschappij4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maatschappij5", DbType="VarChar(50)")]
		public string Maatschappij5
		{
			get
			{
				return this._Maatschappij5;
			}
			set
			{
				if ((this._Maatschappij5 != value))
				{
					this._Maatschappij5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maatschappij6", DbType="VarChar(50)")]
		public string Maatschappij6
		{
			get
			{
				return this._Maatschappij6;
			}
			set
			{
				if ((this._Maatschappij6 != value))
				{
					this._Maatschappij6 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maatschappij7", DbType="VarChar(50)")]
		public string Maatschappij7
		{
			get
			{
				return this._Maatschappij7;
			}
			set
			{
				if ((this._Maatschappij7 != value))
				{
					this._Maatschappij7 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maatschappij8", DbType="VarChar(50)")]
		public string Maatschappij8
		{
			get
			{
				return this._Maatschappij8;
			}
			set
			{
				if ((this._Maatschappij8 != value))
				{
					this._Maatschappij8 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OverigeOpmerkingen", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string OverigeOpmerkingen
		{
			get
			{
				return this._OverigeOpmerkingen;
			}
			set
			{
				if ((this._OverigeOpmerkingen != value))
				{
					this._OverigeOpmerkingen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GrafVak", DbType="VarChar(50)")]
		public string GrafVak
		{
			get
			{
				return this._GrafVak;
			}
			set
			{
				if ((this._GrafVak != value))
				{
					this._GrafVak = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GrafPlaats", DbType="VarChar(50)")]
		public string GrafPlaats
		{
			get
			{
				return this._GrafPlaats;
			}
			set
			{
				if ((this._GrafPlaats != value))
				{
					this._GrafPlaats = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GrafTelefoon", DbType="VarChar(50)")]
		public string GrafTelefoon
		{
			get
			{
				return this._GrafTelefoon;
			}
			set
			{
				if ((this._GrafTelefoon != value))
				{
					this._GrafTelefoon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Polis1", DbType="VarChar(50)")]
		public string Polis1
		{
			get
			{
				return this._Polis1;
			}
			set
			{
				if ((this._Polis1 != value))
				{
					this._Polis1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Polis2", DbType="VarChar(50)")]
		public string Polis2
		{
			get
			{
				return this._Polis2;
			}
			set
			{
				if ((this._Polis2 != value))
				{
					this._Polis2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Polis3", DbType="VarChar(50)")]
		public string Polis3
		{
			get
			{
				return this._Polis3;
			}
			set
			{
				if ((this._Polis3 != value))
				{
					this._Polis3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Polis4", DbType="VarChar(50)")]
		public string Polis4
		{
			get
			{
				return this._Polis4;
			}
			set
			{
				if ((this._Polis4 != value))
				{
					this._Polis4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Polis5", DbType="VarChar(50)")]
		public string Polis5
		{
			get
			{
				return this._Polis5;
			}
			set
			{
				if ((this._Polis5 != value))
				{
					this._Polis5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Polis6", DbType="VarChar(50)")]
		public string Polis6
		{
			get
			{
				return this._Polis6;
			}
			set
			{
				if ((this._Polis6 != value))
				{
					this._Polis6 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Polis7", DbType="VarChar(50)")]
		public string Polis7
		{
			get
			{
				return this._Polis7;
			}
			set
			{
				if ((this._Polis7 != value))
				{
					this._Polis7 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Polis8", DbType="VarChar(50)")]
		public string Polis8
		{
			get
			{
				return this._Polis8;
			}
			set
			{
				if ((this._Polis8 != value))
				{
					this._Polis8 = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
